### ISSUE TITLE
PDF Error

### ISSUE THREAD

**Issue by kjsauer** [kurt-rhee/product-management-notes#1]
Hello, I'm interested in checking out this PDF, however, I'm getting an error when trying to download the PDF.

"""
Error rendering embedded code

Invalid PDF
"""

Thanks.

**Comment by kjsauer** [comment]
P.S. It works when you click "Download raw file". So, please feel free to close this GitHub Issue! Thanks again.

**Comment by kurt-rhee** [comment]
Nice glad you found a workaround!
